### ISSUE TITLE
Poetry warning

### ISSUE THREAD

**Issue by smithna** [deusebio/Graph-Machine-Learning#14]
Running `poetry install` in Chapter01 directory yields this warning.

`Warning: The current project could not be installed: No file/folder found for package chapter01
If you do not want to install the current project use --no-root.
If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
In a future version of Poetry this warning will become an error!`

**Comment by deusebio** [comment]
Hi @smithna !

Thank you for submitting the issue. Yes, that's a good point. I've just raised a PR to fix this by setting `package-mode=false` in all `pyproject.toml` files. Poetry is used for managing the dependencies rather than for packaging. So I believe the change you suggst is very appropriate. 

Bear in mind that we don't require people for having `poetry` or installing the environment using `poetry install`, as we also provide the `requirements.txt` file to be installed using `pip`

**Comment by deusebio** [comment]
PR has been merged! @smithna feel free to re-open if you are still experiencing issues. Thanks
